
var PLAYER_START_X = 0;
var PLAYER_START_Y = 0;
var PLAYER_START_Z = 0;
var PLAYER_START_SIZE = 32;
var PLAYER_START_COLOR = 0;
var PLAYER_START_NAME = 0;

var AXE_SIZE = 4;

var LEVEL_WIDTH = 4096;
var LEVEL_HEIGHT = 128;
var LEVEL_DEPTH = 4096;

var START_Y = 32;
