
var PLAYER_START_X = 0;
var PLAYER_START_Y = 0;
var PLAYER_START_Z = 0;
var PLAYER_START_SIZE = 128;
var PLAYER_START_COLOR = 0;
var PLAYER_START_NAME = 0;

var AXE_SIZE = 16;

var LEVEL_WIDTH = 16384;
var LEVEL_HEIGHT = 512;
var LEVEL_DEPTH = 16384;

var START_Y = 32;
